### ISSUE TITLE
JSON Notes

### ISSUE THREAD

**Issue by stendewa** [learn-co-curriculum/dsc-json-v2-1#5]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ X] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

## Any Additional Context?

Use Comments when writing the codes, ANY CODE! Learners need to know what's happening not just syntax!

**Comment by bpurdy-ds** [comment]
Hello, @stendewa for the suggestion. We're in the process of updating this content, so we've made a note to add comments to the code chunks for the new version of this notebook. We appreciate the feedback and taking the time to reach out.
